export const TRIAGE_FETCH_SUCCESS = 'TRIAGE_FETCH_SUCCESS';
export const TIME_OF_CONFIRMED_COVID_RESETED =
  'TIME_OF_CONFIRMED_COVID_RESETED';
export const WHOLE_TRIAGE_UPDATED = 'WHOLE_TRIAGE_UPDATED';
export const REVOKE_TOR_STATUS_FINISHED = 'REVOKE_TOR_STATUS_FINISHED';
export const REVOKE_MANUAL_COVID_FINISHED = 'REVOKE_MANUAL_COVID_FINISHED';
export const CONFIRM_MANUAL_COVID_FINISHED = 'CONFIRM_MANUAL_COVID_FINISHED';
