export const TRIAGE_FETCH_REQUESTED = 'TRIAGE_FETCH_REQUESTED';
export const TRIAGE_FETCH_SUCCESS = 'TRIAGE_FETCH_SUCCESS';
export const TIME_OF_CONFIRMED_COVID_RESETED =
  'TIME_OF_CONFIRMED_COVID_RESETED';
export const WHOLE_TRIAGE_UPDATED = 'WHOLE_TRIAGE_UPDATED';
export const REVOKE_TOR_STATUS_FINISHED = 'REVOKE_TOR_STATUS_FINISHED';
