stages:
  - build
  - deploy

.build: &build
  image: node:13
  stage: build
  script:
    - yarn audit --groups dependencies
    - yarn install
    - yarn build
  artifacts:
    expire_in: 30 minutes
    paths:
      - build

build:latest:
  <<: *build
  before_script:
    - echo "$STAGE_ENV" > .env
  except:
    - master
    - /^release/

build:release:
  <<: *build
  artifacts:
    expire_in: 12 hours
    paths:
      - build
  before_script:
    - echo "$STAGE_ENV" > .env
  only:
    - master
    - /^release/

.deploy: &deploy
  image: dockito/lftp-client
  stage: deploy

deploy:dev:
  <<: *deploy
  script:
    - lftp -e 'mirror -R build /safesafe-dev; bye' -u $STAGE_FTP_USER,$STAGE_FTP_PASS $STAGE__FTP_HOST
  when: manual

deploy:stage:
  <<: *deploy
  script:
    - lftp -e 'mirror -R build /safesafe-stage; ; bye' -u $STAGE_FTP_USER,$STAGE_FTP_PASS $STAGE__FTP_HOST
  only:
    - master
    - /^release/
