export const LIST_ACTIVITIES_SUCCESS = 'LIST_ACTIVITIES_SUCCESS';
export const MARK_ACTIVITY_AS_READ = 'MARK_ACTIVITY_AS_READ';
export const MARK_ALL_ACTIVITIES_AS_READ = 'MARK_ALL_ACTIVITIES_AS_READ';
