export const FETCH_DISTRICTS_STATUS_SUCCESS = 'FETCH_DISTRICTS_STATUS_SUCCESS';
export const FETCH_SUBSCRIBED_DISTRICTS_SUCCESS = 'FETCH_SUBSCRIBED_DISTRICTS_SUCCESS';
export const SUBSCRIBED_DISTRICTS_SUCCESS = 'SUBSCRIBED_DISTRICTS_SUCCESS';
export const UNSUBSCRIBED_DISTRICTS_SUCCESS = 'UNSUBSCRIBED_DISTRICTS_SUCCESS';
