export const FETCH_SUMMARY_STATISTICS_SUCCESS = 'FETCH_SUMMARY_STATISTICS_SUCCESS';
export const FETCH_DETAILS_STATISTICS_SUCCESS = 'FETCH_DETAILS_STATISTICS_SUCCESS';
export const FETCH_EXPOSURE_AGGREGATE_STATISTICS = 'FETCH_EXPOSURE_AGGREGATE_STATISTICS';
