export const FIELD_AGE = 'age';
export const FIELD_SEX = 'sex';
export const FIELD_NAME = 'name';
export const FIELD_CHRONIC_SICK_1 = 'nadciśnienie tętnicze';
export const FIELD_CHRONIC_SICK_1_PH = 'jak długo? podać w latach z dokładnością do 0.25 roku';
export const FIELD_CHRONIC_SICK_2 = 'przewlekłe choroby układu oddechowego';
export const FIELD_CHRONIC_SICK_2_PH = 'proszę wpisać jakie';
export const FIELD_CHRONIC_SICK_3 = 'choroby układu krążenia - choroba niedokrwienna serca';
export const FIELD_CHRONIC_SICK_4 = 'choroby układu krążenia - wady zastawkowe serca';
export const FIELD_CHRONIC_SICK_5 = 'choroby układu krążenia - niewydolność serca';
export const FIELD_CHRONIC_SICK_6 = 'choroby układu krążenia - inne';
export const FIELD_CHRONIC_SICK_6_PH = 'proszę wpisać jakie';
export const FIELD_CHRONIC_SICK_7 = 'cukrzyca - insulinozależna';
export const FIELD_CHRONIC_SICK_8 = 'cukrzyca - insulinoniezależna';
export const FIELD_CHRONIC_SICK_9 = 'choroby układu immunologicznego';
export const FIELD_CHRONIC_SICK_9_PH = 'proszę wpisać jakie';
export const FIELD_CHRONIC_SICK_10 = 'stosowanie leków obniżających odporność (immunosupresyjnych)';
export const FIELD_CHRONIC_SICK_10_PH = 'proszę wpisać jakie';
export const FIELD_CHRONIC_SICK_11 = 'choroby onkologiczne';
export const FIELD_CHRONIC_SICK_11_PH = 'proszę wpisać jakie podać w latach z dokładnością do 0.25 roku';
export const FIELD_CHRONIC_SICK_12 = 'nietolerancje/alergie/nadwrażliwość na leki';
export const FIELD_CHRONIC_SICK_12_PH = 'proszę wpisać jakie podać w latach z dokładnością do <=1 , <3, <5, <10 <15 lub więcej niż 15 >lat';
export const FIELD_CHRONIC_SICK_13 = 'nietolerancje/alergie - pokarmowe';
export const FIELD_CHRONIC_SICK_13_PH = 'proszę wpisać jakie';
export const FIELD_CHRONIC_SICK_14 = 'nietolerancje/alergie - oddechowe';
export const FIELD_CHRONIC_SICK_14_PH = 'proszę wpisać jakie';
export const FIELD_CHRONIC_SICK_15 = 'nietolerancje/alergie - inne';
export const FIELD_CHRONIC_SICK_15_PH = 'proszę wpisać jakie';
export const FIELD_CHRONIC_SICK_1_DESC = 'chronic_sick_1_desc';
export const FIELD_CHRONIC_SICK_2_DESC = 'chronic_sick_2_desc';
export const FIELD_CHRONIC_SICK_3_DESC = 'chronic_sick_3_desc';
export const FIELD_CHRONIC_SICK_4_DESC = 'chronic_sick_4_desc';
export const FIELD_CHRONIC_SICK_5_DESC = 'chronic_sick_5_desc';
export const FIELD_CHRONIC_SICK_6_DESC = 'chronic_sick_6_desc';
export const FIELD_CHRONIC_SICK_7_DESC = 'chronic_sick_8_desc';
export const FIELD_CHRONIC_SICK_8_DESC = 'chronic_sick_9_desc';
export const FIELD_CHRONIC_SICK_9_DESC = 'chronic_sick_10_desc';
export const FIELD_CHRONIC_SICK_10_DESC = 'chronic_sick_11_desc';
export const FIELD_CHRONIC_SICK_11_DESC = 'chronic_sick_12_desc';
export const FIELD_CHRONIC_SICK_12_DESC = 'chronic_sick_13_desc';
export const FIELD_CHRONIC_SICK_13_DESC = 'chronic_sick_14_desc';
export const FIELD_CHRONIC_SICK_14_DESC = 'chronic_sick_15_desc';
export const FIELD_CHRONIC_SICK_15_DESC = 'chronic_sick_16_desc';
export const FIELD_BLOOD_GROUP = 'bloodGroup';

export const VALUE_MAN = 'male';
export const VALUE_WOMAN = 'female';

export const FIELD_CHOICE_ID = 'choice_id';
export const FIELD_ITEM_ID = 'item_id';

export const VALUE_PRESENT = 'present';
export const VALUE_ABSENT = 'absent';

export const ANDROID = 'Android';
export const IOS = 'iOS';

export const FIELD_TEMPERATURE = 'temperature';
export const FIELD_RUNNY_NOSE = 'runnyNose';
export const FIELD_COUGH = 'cough';
export const FIELD_CHILLS = 'chills';
export const FIELD_MUSCLE_PAIN = 'musclePain';
export const FIELD_CONTACTS = 'contacts';
export const FIELD_SMOKE = 'smoke';
export const FIELD_SMOKE_NUMBER = 'smokeNumber';

export const VALUE_SYMPTOM_LEVEL_1 = 'level 1';
export const VALUE_SYMPTOM_LEVEL_2 = 'level 2';
export const VALUE_SYMPTOM_LEVEL_3 = 'level 3';
export const VALUE_SYMPTOM_LEVEL_4 = 'level 4';

export const VALUE_BLOOD_GROUP_ABPLUS = 'AB+';
export const VALUE_BLOOD_GROUP_ABMINUS = 'AB-';
export const VALUE_BLOOD_GROUP_APLUS = 'A+';
export const VALUE_BLOOD_GROUP_AMINUS = 'A-';
export const VALUE_BLOOD_GROUP_BPLUS = 'B+';
export const VALUE_BLOOD_GROUP_BMINUS = 'B-';
export const VALUE_BLOOD_GROUP_0PLUS = '0+';
export const VALUE_BLOOD_GROUP_0MINUS = '0-';
export const VALUE_BLOOD_GROUP_UNDEFINED = 'nie wiem';
export const VALUE_SMOKE_YES = 'tak';
export const VALUE_SMOKE_NO = 'nie';
export const VALUE_SMOKE_NUMBER_1 = '1-5 sztuk';
export const VALUE_SMOKE_NUMBER_2 = '6-10 sztuk';
export const VALUE_SMOKE_NUMBER_3 = '11-20 sztuk';
export const VALUE_SMOKE_NUMBER_4 = '20-40 sztuk';
export const VALUE_SMOKE_NUMBER_5 = 'ponad 40';
