import { Routes } from './routes';
import {
  AddTranslation,
  CurrentRestrictions,
  Daily,
  DailyData,
  Diagnosis,
  HistoryActivities,
  HowItWorks,
  IAmSick,
  ImportantInfo,
  LabTest,
  PrivacyPolicy,
  PrivacyPolicyDetails,
  Regulations,
  ReportBug,
  ResultLabTest,
  RiskTest,
  RiskTestData,
  MenuSettings,
  Settings,
  SettingsLanguages,
  SummaryRiskTest,
  UploadHistoricalData,
  UserData,
  UserDataChange,
  UserDataSettings,
  WarningInEurope
} from '../../views';

export const Screens = {
  [Routes.AddTranslation]: AddTranslation,
  [Routes.CurrentRestrictions]: CurrentRestrictions,
  [Routes.Daily]: Daily,
  [Routes.DailyData]: DailyData,
  [Routes.Diagnosis]: Diagnosis,
  [Routes.HistoryActivities]: HistoryActivities,
  [Routes.HowItWorks]: HowItWorks,
  [Routes.IAmSick]: IAmSick,
  [Routes.ImportantInformation]: ImportantInfo,
  [Routes.LabTest]: LabTest,
  [Routes.LabTestResult]: ResultLabTest,
  [Routes.PrivacyPolicy]: PrivacyPolicy,
  [Routes.PrivacyPolicyDetails]: PrivacyPolicyDetails,
  [Routes.Regulations]: Regulations,
  [Routes.ReportBug]: ReportBug,
  [Routes.RiskTest]: RiskTest,
  [Routes.RiskTestData]: RiskTestData,
  [Routes.Settings]: MenuSettings,
  [Routes.SettingsBluetooth]: Settings,
  [Routes.SettingsLanguages]: SettingsLanguages,
  [Routes.SummaryRiskTest]: SummaryRiskTest,
  [Routes.UploadHistoricalData]: UploadHistoricalData,
  [Routes.UserData]: UserData,
  [Routes.UserDataChange]: UserDataChange,
  [Routes.UserDataSettings]: UserDataSettings,
  [Routes.WarningInEurope]: WarningInEurope
};
