export const ONBOARDING_IOS_BLUETOOTH_SUMMARY_SHOWED =
  'ONBOARDING_IOS_BLUETOOTH_SUMMARY_SHOWED';
export const ONBOARDING_NOTIFICATION_PERMISSION_SHOWED =
  'ONBOARDING_NOTIFICATION_PERMISSION_SHOWED';
export const ONBOARDING_BLUETOOTH_PERMISSION_SHOWED =
  'ONBOARDING_BLUETOOTH_PERMISSION_SHOWED';
