export const ONBOARDING_FINISHED = 'ONBOARDING_FINISHED';
export const EXPOSURE_ONBOARDING_FINISHED = 'EXPOSURE_ONBOARDING_FINISHED';
export const START_SCREEN_SHOWED = 'START_SCREEN_SHOWED';
export const UPLOAD_HISTORICAL_DATA_REQUESTED =
  'UPLOAD_HISTORICAL_DATA_REQUESTED';
export const UPLOAD_HISTORICAL_DATA_FINISHED =
  'UPLOAD_HISTORICAL_DATA_FINISHED';
export const UPLOAD_HISTORICAL_DATA_ENDED = 'UPLOAD_HISTORICAL_DATA_ENDED';
export const FIRST_DIAGNOSIS_FINISHED = 'FIRST_DIAGNOSIS_FINISHED';
export const MIGRATION_FINISHED = 'MIGRATION_FINISHED';
export const APP_STATE_CLEARED = 'APP_STATE_CLEARED';
export const DATA_FROM_NEWEST_VERSION_MARKED =
  'DATA_FROM_NEWEST_VERSION_MARKED';
export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';
export const BLUETOOTH_DATA_CLEARED = 'BLUETOOTH_DATA_CLEARED';
export const UPLOAD_HISTORICAL_DATA_ERROR_MESSAGE_HIDDEN =
  'UPLOAD_HISTORICAL_DATA_ERROR_MESSAGE_HIDDEN';
