export const ONBOARDING_FINISHED = 'ONBOARDING_FINISHED';
export const ONBOARDING_IOS_BLUETOOTH_SUMMARY_SHOWED =
  'ONBOARDING_IOS_BLUETOOTH_SUMMARY_SHOWED';
export const ONBOARDING_NOTIFICATION_PERMISSION_SHOWED =
  'ONBOARDING_NOTIFICATION_PERMISSION_SHOWED';
export const ONBOARDING_BLUETOOTH_PERMISSION_SHOWED =
  'ONBOARDING_BLUETOOTH_PERMISSION_SHOWED';
export const IOS_ONBOARDING_SCREEN_NOTIFICATION_SHOWED =
  'IOS_ONBOARDING_SCREEN_NOTIFICATION_SHOWED';
export const START_SCREEN_SHOWED = 'START_SCREEN_SHOWED';
