export { Daily } from './Daily';
export { Diagnosis } from './Diagnosis';
export { Home } from './Home';
export { HowItWorks } from './HowItWorks';
export { RiskTest } from './RiskTest';
export { Numbers } from './Numbers';
export { PrivacyPolicy } from './PrivacyPolicy';
export { Registration } from './Registration';
export { Regulations } from './Regulations';
