export const ROUTE_CHANGED = 'ROUTE_CHANGED';
export const BACK_PRESSED = 'BACK_PRESSED';
export const GO_TO_PREVIOUS_ROUTE_SUCCESS = 'GO_TO_PREVIOUS_ROUTE_SUCCESS';
export const RESET_NAVIGATION_STATE = 'RESET_NAVIGATION_STATE';
export const SET_NAVIGATION_ROOT = 'SET_NAVIGATION_ROOT';
