export const ROUTE_CHANGED = 'ROUTE_CHANGED';
export const GO_TO_PREVIOUS_ROUTE_REQUESTED = 'GO_TO_PREVIOUS_ROUTE_REQUESTED';
export const GO_TO_PREVIOUS_ROUTE_SUCCESS = 'GO_TO_PREVIOUS_ROUTE_SUCCESS';
