export const NATIVE_DATA_FETCH_NOTIFICATION_SUCCESS =
  'NATIVE_DATA/GET_NOTIFICATION_SUCCESS';
export const NATIVE_DATA_FETCH_SERVICES_STATUS_SUCCESS =
  'NATIVE_DATA/GET_SERVICES_STATUS_SUCCESS';
export const NATIVE_DATA_FETCH_EXPOSURE_NOTIFICATION_STATISTICS_SUCCESS =
  'NATIVE_DATA/GET_EXPOSURE_NOTIFICATION_STATISTICS_SUCCESS';
export const NATIVE_DATA_FETCH_NATIVE_STATE = 'NATIVE_DATA/GET_NATIVE_STATE';
export const NATIVE_DATA_HIDE_NOTIFICATION_SUCCESS =
  'NATIVE_DATA/HIDE_NOTIFICATION_SUCCESS';
export const NATIVE_DATA_SET_SERVICES_STATUS_SUCCESS =
  'NATIVE_DATA/SET_SERVICES_STATUS_SUCCESS';
export const NATIVE_DATA_SET_SERVICE_STATUS_SOURCE_RESETED =
  'NATIVE_DATA/SET_SERVICE_STATUS_SOURCE_RESETED';
export const FETCH_VERSION_SUCCESS = 'FETCH_VERSION_SUCCESS';
export const FETCH_LANGUAGE = 'FETCH_LANGUAGE';
export const UPLOAD_TEST_PIN_FINISHED = 'UPLOAD_TEST_PIN_FINISHED';
export const RESET_UPLOAD_TEST_PIN_RESULT_SUCCESS =
  'RESET_UPLOAD_TEST_PIN_RESULT_SUCCESS';
