const Routes = {
  AddTranslation: '/add-translation',
  AdviceInformation: '/advice',
  CurrentRestrictions: '/current-restrictions',
  Daily: '/daily',
  DailyData: '/daily-data',
  Diagnosis: '/diagnosis',
  FaqPage: '/faq',
  Home: '/',
  HospitalsList: '/hospitals-list',
  HowItWorks: '/how-it-works',
  IAmSick: '/i-am-sick',
  ImportantInformation: '/important-info',
  LabTest: '/lab-test',
  NoRiskInformation: '/risk-information/no_risk',
  PrivacyPolicy: '/privacy-policy',
  PrivacyPolicyDetails: '/privacy-policy-details',
  Regulations: '/regulations',
  ReportBug: '/report-bug',
  RiskTest: '/risk-test',
  Settings: '/settings',
  SettingsBluetooth: '/settings/bluetooth',
  SettingsLanguages: '/settings/languages',
  Start: '/start',
  SummaryRiskTest: '/summary-risk-test',
  UploadHistoricalData: '/upload-historical-data',
  UserData: '/user-data',
  UserDataChange: '/user-data/change',
  UserDataSettings: '/user-data/settings'
};

export default Routes;
