const Routes = {
  Home: '/',
  Start: '/start',
  AddTranslation: '/add-translation',
  Daily: '/daily',
  DailyData: '/daily-data',
  RiskTest: '/risk-test',
  HowItWorks: '/how-it-works',
  IAmSick: '/i-am-sick',
  EmergencyNumbers: '/numbers',
  NoRiskInformation: '/risk-information/no_risk',
  PrivacyPolicy: '/privacy-policy',
  PrivacyPolicyDetails: '/privacy-policy-details',
  Settings: '/settings',
  SettingsBluetooth: '/settings/bluetooth',
  SettingsLanguages: '/settings/languages',
  Regulations: '/regulations',
  Diagnosis: '/diagnosis',
  UserData: '/user-data',
  UserDataChange: '/user-data/change',
  UserDataSettings: '/user-data/settings',
  HospitalsList: '/hospitals-list',
  ReportBug: '/report-bug',
  AdviceInformation: '/advice',
  FaqPage: '/faq',
  UploadHistoricalData: '/upload-historical-data',
  ImportantInformation: '/important-info'
};

export default Routes;
